steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "frontend/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/zk-hash-frontend:$BUILD_ID",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/zk-hash-frontend:$BUILD_ID"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy zk-hash-frontend \
          --image gcr.io/$PROJECT_ID/zk-hash-frontend:$BUILD_ID \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated

images:
  - "gcr.io/$PROJECT_ID/zk-hash-frontend:$BUILD_ID"
